name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alinuxsa/go-dev:1.17.5
      
    - name: Login docker hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secret.DOCKER_USERNAME }}
        password: ${{ secret.DOCKER_PASSWORD }}
    - name: Push Docker Image
      run: docker push alinuxsa/go-dev:1.17.5
