name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alinuxsa/go-dev:1.17.5
      
    - name: Login docker hub
      env: 
        DOCKER_USER: ${secret.DOCKER_USERNAME}
        DOCKER_PASSWORD: ${secret.DOCKER_USERNAME}
      run: echo $DOCKER_PASSWORD |  docker login -u $DOCKER_USER --password-stdin
    - name: Push Docker Image
      run: docker push alinuxsa/go-dev:1.17.5
